language: node_js
arch:
    - amd64
    - ppc64le
notifications:
    email:
        on_success: never
        on_failure: change
node_js:
    - "12"
    - "15"
    - "16"
cache:
    npm: true
install:
    - npm install
