version: 2.1
orbs:
    node: circleci/node@5.0.3
jobs:
    install-node-example:
        docker:
            - image: "cimg/base:stable"
        working_directory: ~/repo
        resource_class: small
        steps:
            - checkout
            - run:
                  name: list all my file
                  command: ls -al
            - restore_cache:
                  keys:
                      - v1-{{ checksum "package.json" }}
                      - v1-
            - node/install:
                  install-yarn: false
                  node-version: "14.13"
            - run:
                  name: install node_modules
                  command: npm install
            - run: ls -la
            - save_cache:
                  key: v1-{{ checksum "package.json" }}
                  paths:
                      - node_modules
            - run: node --version
    publish:
        docker:
            - image: "cimg/node:17"
        working_directory: ~/repo
        resource_class: small
        steps:
            - run:
                  name: list all my files
                  command: |
                      ls -la
            - run:
                  name: Publish to NPM
                  command: |
                      npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
                      npm publish
workflows:
    version: 2
    test_my_app:
        jobs:
            - install-node-example
            - node/test:
                  requires:
                      - install-node-example
                  test-results-for: jest
                  test-results-path: junit.xml
            - publish:
                  requires:
                      - node/test
