version: 2.1
orbs:
    node: circleci/node@5.0.3
jobs:
    Fetch-Code:
        docker:
            - image: "cimg/base:stable"
        resource_class: small
        working_directory: ~/repo
        steps:
            - run:
                  name: greeting
                  command: echo 'hello world'
            - checkout
            - run:
                  name: list all my file
                  command: ls -al
    install-node-example:
        docker:
            - image: "cimg/base:stable"
        resource_class: small
        steps:
            - restore_cache:
                  keys:
                      - v1-{{ checksum "package.json" }}
                      - v1-
            - node/install:
                  install-yarn: false
                  node-version: "14.13"
            - save_cache:
                  key: v1-{{ checksum "package.json" }}
                  paths:
                      - ~/node_modules
            - run: node --version
workflows:
    test_my_app:
        jobs:
            - Fetch-Code
            - install-node-example:
                  requires:
                      - Fetch-Code
            - node/test:
                  requires:
                      - install-node-example
                  test-results-for: jest
                  test-results-path: junit.xml
