version: 2.1

jobs:
    test:
        docker:
            - image: cimg/node:14.13.0
        resource_class: small
        steps:
            - checkout
            - node/install-packages:
              pkg-manager: npm
            - run:
              name: check node version
              command: node --version
            - run:
              name: Run tests
              command: npm test
workflows:
    test-deploy:
        jobs:
            - test
