version: 2.1

jobs:
    greeting:
        docker:
            - image: cimg/base:stable
        resource_class: small
        steps:
            - run:
                  name: say hello
                  command: |
                      echo 'hello world'
    Fetch-Code:
        docker:
            - image: cimg/node:14.13.0
        resource_class: small
        steps:
            - checkout
            - run:
                  name: install node
                  command: ls -al
    build:
        docker:
            - image: cimg/node:14.13.0
        resource_class: small
        steps:
            - node/install-packages:
                  pkg-manager: npm
            - run:
                  name: test app
                  command: npm test
workflows:
    version: 2
    build_and_test:
        jobs:
            - greeting
            - Fetch-Code:
                  requires:
                      - greeting
            - build:
                  requires:
                      - Fetch-Code
