version: 2.1

parameters:
    run_flyway:
        type: boolean
        default: false
        
executors:
    docker-executor:
        docker:
            - image: "cimg/base:stable"
        working_directory: ~/repo
        resource_class: small
orbs:
    node: circleci/node@5.0.3
jobs:
    install-node-example:
        executor: docker-executor
        steps:
            - checkout
            - setup_remote_docker:
                  docker_layer_caching: true
            - run:
                  name: list all my file
                  command: ls -al
            - run: 
                  name: list circle token
                  command: echo ${CIRCLECI_TOKEN}
            # - run: curl -u ${CIRCLECI_TOKEN} -X POST --header 'Content-Type: application/json' -d '{"parameters": {"run_flyway": ${FLYWAY_EXECUTE} }}' https://circleci.com/api/v2/project/:project_slug/pipeline    
            - restore_cache:
                  keys:
                      - v1-{{ checksum "package.json" }}
                      - v1-
            - node/install:
                  install-yarn: false
                  node-version: "14.13"
            - run:
                  name: install node_modules
                  command: npm install
            - run: ls -la
            - save_cache:
                  key: v1-{{ checksum "package.json" }}
                  paths:
                      - node_modules
            - run: node --version
            - store_artifacts:
                  path: /tmp/artifact-1
                  destination: artifact-file
    test_to_run:
        executor: docker-executor
        steps:
            - checkout
            - run: echo 'this is test_to_run step'
            - run: ls
            - when:
                condition:
                    equals: [ 'true', $<< pipeline.parameters.run_flyway >> ]
                steps:
                    - run: echo 'flyway execute'
                    - run: echo "flyway execute here"
            - run: echo 0
    publish:
        executor: docker-executor
        steps:
            - checkout
            - run:
                  name: list all my files
                  command: |
                      ls -la
            - node/install:
                  install-yarn: false
                  node-version: "14.13"
            - run:
                  name: install node_modules
                  command: npm install
            - run:
                  name: Publish to NPM
                  command: |
                      npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
                      npm publish
workflows:
    version: 2
    test_my_app:
        jobs:
            - install-node-example
            - node/test:
                  requires:
                      - install-node-example
                  test-results-for: jest
                  test-results-path: junit.xml
            - hold:
                  type: approval
                  requires:
                      - install-node-example
            - publish:
                  requires:
                      - hold
                  filters:
                      branches: 
                          only: master
    test_deploy_flyway:
        when: << pipeline.parameters.run_flyway >>
        jobs:
            - test_to_run
