version: 2.1

jobs:
    test:
        docker:
            - image: cimg/node:14.13.0
        resource_class: small
        steps:
            - checkout
            - run: node --version
            - run: ls -a
workflows:
    test-deploy:
        jobs:
            - test
