version: 2.1

jobs:
    build:
        docker:
            - image: cimg/node:14.13.0
        resource_class: small
        steps:
            - checkout
            - run:
                  name: install node
                  command: npm install
            - run:
                  name: check node version
                  command: node --version
    test:
        docker:
            - image: cimg/node:14.13.0
        resource_class: small
        steps:
            - run:
                  name: Run tests
                  command: npm test
workflows:
    version: 2
    build_and_test:
        jobs:
            - build
            - test
