version: 2.1

obs:
    node: circleci/node@5.0.3

jobs:
    greeting:
        docker:
            - image: cimg/base:stable
        resource_class: small
        steps:
            - run:
                  name: say hello
                  command: |
                      echo 'hello world'
    Fetch-Code:
        docker:
            - image: cimg/node:14.13.0
        resource_class: small
        steps:
            - checkout
            - run:
                  name: install node
                  command: ls -al
    Build:
        docker:
            - image: cimg/base:stable
        resource_class: small
        steps:
            - run: ls -al
            - node/install:
                  pkg-manager: npm
            - node/test:
                  test-results-for: jest
workflows:
    version: 2
    build_and_test:
        jobs:
            - greeting
            - Fetch-Code:
                  requires:
                      - greeting
            - Build:
                  requires:
                      - Fetch-Code
            - test:
                  jobs:
                      - node/test:
                            test-results-for: jest
